#This is the raw code for the Maize MaxEnt Model projecting to current global climate data

#This is how it actually works and this is max memory
mkdir /scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/Ab10_MaxEntStand4_SSPCurrent
java -mx40000000m -jar maxent.jar nowarnings noprefixes -E "" -E Ab10 responsecurves jackknife outputformat=logistic outputdirectory=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/Ab10_MaxEntStand4_SSPCurrent projectionlayers=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/MaxEnt_EnvData_Subset/projection samplesfile=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/SGE_GPS_MaxEnt_Format.csv environmentallayers=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/MaxEnt_EnvData_Subset/stand randomseed noaskoverwrite randomtestpoints=25 betamultiplier=3.0 replicates=10 replicatetype=subsample threshold writeplotdata noautofeature nooutputgrids threads=24 defaultprevalence=0.06 -t sq1.stand -t sq3.stand -t sq4.stand -t sq5.stand -t sq6.stand -N wc2.1_30s_srad_03.stand -N wc2.1_30s_srad_07.stand -N wc2.1_30s_srad_10.stand -N wc2.1_30s_wind_06.stand autorun

mkdir /scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/BChrom_MaxEntStand4_SSPCurrent
java -mx40000000m -jar maxent.jar nowarnings noprefixes -E "" -E BChrom responsecurves jackknife outputformat=logistic outputdirectory=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/BChrom_MaxEntStand4_SSPCurrent projectionlayers=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/MaxEnt_EnvData_Subset/projection samplesfile=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/SGE_GPS_MaxEnt_Format.csv environmentallayers=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/MaxEnt_EnvData_Subset/stand randomseed noaskoverwrite randomtestpoints=25 betamultiplier=3.0 replicates=10 replicatetype=subsample threshold writeplotdata noautofeature nooutputgrids threads=24 defaultprevalence=0.12 -t sq1.stand -t sq3.stand -t sq4.stand -t sq5.stand -t sq6.stand -N wc2.1_30s_srad_03.stand -N wc2.1_30s_srad_07.stand -N wc2.1_30s_srad_10.stand -N wc2.1_30s_wind_06.stand autorun

mkdir /scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/K10L2_MaxEntStand4_SSPCurrent
java -mx40000000m -jar maxent.jar nowarnings noprefixes -E "" -E K10L2 responsecurves jackknife outputformat=logistic outputdirectory=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/K10L2_MaxEntStand4_SSPCurrent projectionlayers=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/MaxEnt_EnvData_Subset/projection samplesfile=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/SGE_GPS_MaxEnt_Format.csv environmentallayers=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/MaxEnt_EnvData_Subset/stand randomseed noaskoverwrite randomtestpoints=25 betamultiplier=3.0 replicates=10 replicatetype=subsample threshold writeplotdata noautofeature nooutputgrids threads=24 defaultprevalence=0.05 -t sq1.stand -t sq3.stand -t sq4.stand -t sq5.stand -t sq6.stand -N wc2.1_30s_srad_03.stand -N wc2.1_30s_srad_07.stand -N wc2.1_30s_srad_10.stand -N wc2.1_30s_wind_06.stand autorun

mkdir /scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/Maize_MaxEntStand4_SSPCurrent
java -mx40000000m -jar maxent.jar nowarnings noprefixes -E "" -E Maize responsecurves jackknife outputformat=logistic outputdirectory=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/Maize_MaxEntStand4_SSPCurrent projectionlayers=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/MaxEnt_EnvData_Subset/projection samplesfile=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/SGE_GPS_MaxEnt_Format.csv environmentallayers=/scratch/mjb51923/Ab10_Global_Survey/out/WorldClim2/MaxEnt_EnvData_Subset/stand randomseed noaskoverwrite randomtestpoints=25 betamultiplier=3.0 replicates=10 replicatetype=subsample threshold writeplotdata noautofeature nooutputgrids threads=24 defaultprevalence=0.8 -t sq1.stand -t sq3.stand -t sq4.stand -t sq5.stand -t sq6.stand -N wc2.1_30s_srad_03.stand -N wc2.1_30s_srad_07.stand -N wc2.1_30s_srad_10.stand -N wc2.1_30s_wind_06.stand autorun